### PR TITLE
Update install instructions for 1.0

### PR DESCRIPTION
**Pull request by lgessler**

### CODE REVIEW

**Comment by amir-zeldes** [comment]
This looks good, do you need me to package a new release to couple to a master-based Docker?

**Comment by lgessler** [comment]
It should be fine--I think Docker just takes the latest commit from each branch it'd configured to build an image for.

**Comment by lgessler** [comment]
We have [both](https://hub.docker.com/r/gucorpling/gitdox/tags/): the tag `dev` is configured to build from the `dev` branch, and `latest` (the default tag) builds off of `master`.

**Comment by lgessler** [comment]
Needed to revert the fix to #67 since it caused #115.

**Comment by amir-zeldes** [comment]
Looks good. We'll have to think of something else for 'back' at some point, but it's not crucial. Thanks!

**Pull request merged**
