### PR TITLE
Update github3.py

### PR DESCRIPTION
**Pull request by lgessler**
- Remove version lock on github3.py in `requirements.txt`. (Tested with latest release, 1.2.0)
- Reorganize `README.md` slightly, add script for setting up admin password

### CODE REVIEW

**Comment by lgessler** [comment]
The extra commits on this I think are from `gucorpling:dev` not being in sync with `gucorpling:master`.

**Comment by amir-zeldes** [comment]
Looks good, thanks for setting up the admin user too. 

Have you deployed this change to scriptorium's production instance?

**Comment by lgessler** [comment]
Not yet, was waiting for you to take a look. Can do that after this PR is merged.

**Comment by amir-zeldes** [comment]
This looks good, you can go ahead and deploy

**Comment by lgessler** [comment]
I don't have sudo on corpling so I can't install `github3.py==1.2.0`.

**Comment by amir-zeldes** [comment]
So... I just spent a fun hour recovering the server's python 2.6 installation. Turns out, pip upgrades don't take care not to install Python 2.7 syntax, which then completely destroys pip's ability to run due to syntax errors on startup (e.g. 2.7 set notation). 

Many attempts and yums later... I have come back to the point where pip2.6 works again, **but**, it seems github3.py needs `cryptography`, which needs `setuptools>18.5`, but setuptools only supports python2.6 up to V0.7.2. So now I'm stuck with this:

```
Collecting github3.py
  Using cached https://files.pythonhosted.org/packages/a6/21/9055a739fbe7b22a8e99e42906f2c75ba02bab9fd193a85837cd1d6e55d3/github3.py-1.3.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.6.0 (from github3.py)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Requirement already up-to-date: uritemplate>=3.0.0 in /usr/lib/python2.6/site-packages (from github3.py)
Collecting requests>=2.18 (from github3.py)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting jwcrypto>=0.5.0 (from github3.py)
  Using cached https://files.pythonhosted.org/packages/f0/0d/00173a6aee1025e529b21c365182c8d06e78b1beb98d5633f841da6f122e/jwcrypto-0.6.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.6.0->github3.py)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.18->github3.py)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.18->github3.py)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.18->github3.py)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.18->github3.py)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cryptography>=1.5 (from jwcrypto>=0.5.0->github3.py)
  Using cached https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kTiqcq/cryptography/setup.py", line 28, in <module>
        "cryptography requires setuptools 18.5 or newer, please upgrade to a "
    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools
```

Any thoughts on how to get this to run on Python 2.6? Sadly many universities run RHEL6, so 'upgrade to 2.7' is not the best answer here.

**Comment by lgessler** [comment]
Wow! Well let's see, in order of decreasing preference, this is what comes to mind:

1. Assuming all unis would be able to get Docker installed, just drop 2.6 support and insist that they use a Docker image
2. Require admins to install a more recent version of Python somewhere and point all the `#!`'s to that Python rather than the system Python
3. Hand-write the GitHub functionality we need by programming against their HTTP API's
4. Fork github3.py and modify just those parts we need so it's 2.6 compatible

1 and 2 both require that we stop using the system Python, which I think is probably best practice anyway. If 1 isn't possible, then I think 2 is the right way to go.

**Comment by amir-zeldes** [comment]
Ugh... OK, let's try using ourselves as guinea pigs. So if the system Python is 2.7 they have no problem, all good. If we claim RHEL 6 can run this via Docker, we should be able to do that too. The problem I have is that we mess with the file system for custom scriptorium stuff quite a bit (hardwired hacks, SQL into the DB when someone has an onerous update). Can we maintain that and still use docker?

What I like about 3-4, is that our file system stays in tact. But that is a lot of work, so maybe shebanging 2.7 isn't such a bad idea (we do have a compiled 2.7 on corpling).

So what do you think, is docker support and messing with files/sqlite compatible?

**Comment by ctschroeder** [comment]
I’m sorry to see how much work you both have to put into this! If there is something Scriptorium related that is driving this update, and you want to discuss options let me know. Otherwise ignore this comment and know that I appreciate your work very much!

**Comment by amir-zeldes** [comment]
Thanks @ctschroeder , no, it's more general if we want to support larger file commits. The old version of the library we were using for GitHub doesn't support them, so we need to do something about this.

**Pull request merged**
