### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by lgessler**
This PR introduces [a Dockerfile](https://github.com/gucorpling/gitdox/blob/10fad56c46c7b95d806260603ad8dc01bf22e74a/Dockerfile) and tells users [how to install GitDox](https://github.com/gucorpling/gitdox/blob/10fad56c46c7b95d806260603ad8dc01bf22e74a/README.md#installing-with-docker) by manually making a Docker image on their local machine.

Ultimately, we'll probably want to publish a pre-compiled image on [Docker Hub](https://hub.docker.com/) so users will be able to get going with just one command. I've used my personal account in the mean time [to host an image](https://hub.docker.com/r/lgessler/gitdox-dev/). So you can get going with this one magic incantation:

```bash
docker run -dit --restart unless-stopped --name gitdox-dev -p 5000:80 gucorpling/gitdox-dev
```

It should now be running on localhost:5000. See the [updated readme](https://github.com/gucorpling/gitdox/blob/10fad56c46c7b95d806260603ad8dc01bf22e74a/README.md#installing-with-docker) for more information.

### CODE REVIEW

**Comment by amir-zeldes** [comment]
This is terrific, thanks! If you want to set up a Docker Hub group account to match the GitHub organization `gucorpling` you can do that and share the password with the group at the meeting.

**Comment by amir-zeldes** [comment]
Actually let me hold off on merging and you can add that magic incantation to this PR

**Comment by lgessler** [comment]
Ick, false alarm, I got too excited and didn't notice that Ethercalc isn't working. Almost there... 

I'll set up the group account and fix the PR once I fix this.

**Comment by lgessler** [comment]
OK, we now have a [gucorpling organization](https://hub.docker.com/u/gucorpling/) on Docker Hub, and the  Etherpad issue's been fixed.

**Comment by amir-zeldes** [comment]
Fantastic - ready to merge or do you have something in the pipeline still?

**Comment by lgessler** [comment]
It's good to go as far as I can tell! Merge whenever you like.

**Pull request merged**
