### PR TITLE
Redis-based caching, misc bug fixes

### LINKED ISSUE #130: validation oddity
In some of the Apa Johannes documents, the metadata validates in spreadsheet mode, but in the list of docs, the little tag icon for metadata is red. Hovering over the tag reveals a message that "Metadata for license does not match pattern." I can't figure out why this message doesn't appear in the spreadsheet editor window when you validate, nor can I figure out how to fix the validation error. Thanks so much!

### LINKED ISSUE #137: Can't edit corpus metadata
Currently a bug seems to be preventing corpus metadata editing - I think it has something to do with not passing the doc id to the editor metadata service, which then passes None to modules/gitdox_sql, which raises an error when casting the ID as int, but I can't quite pinpoint it. It is possible to delete a corpus metadatum and then add a new one, and it is possible to edit document metadata - just not update corpus metadata.

@lgessler could you take a look?

### LINKED ISSUE #138: Closing tag priority not respected in SGML generation at the end of files
close_tags needs to be sorted again. Will solve this soon.

### PR DESCRIPTION
**Pull request by lgessler**
- New caching layer on top of redis (fixes #130)
- Fix #138 
- Fix #137

### CODE REVIEW

**Comment by lgessler** [comment]
actually hang on, don't merge this yet, some bugs still need to be worked out

**Comment by lgessler** [comment]
ok, this is good to go!

**Comment by amir-zeldes** [comment]
Looks good and mostly performs well live, except export, which on the first run takes very long as predicted, but is then fine. Spreadsheet and export validation from cache is spotty, it seems to hang sometimes but I can't tell why. If it's fast, it's at least as fast as before if not faster, but if it hangs it's noticeably slower than before. Can you take a look on production?

Note we need to keep PY2.6 support due to RHEL6, so please avoid 2.7 syntax (or better turn on 2.6 inspection in your IDE if you're using one). Also, redis 3+ no longer supports PY2.6, so I has to use redis==2.10.6, but that seems to work.

**Comment by lgessler** [comment]
Are you seeing the hanging in the editor page or in the index page?

**Pull request merged**
